const break_1s = '<break time="1s"/>';
const break_2s = '<break time="2s"/>';
const break_3s = '<break time="3s"/>';
const break_5s = '<break time="5s"/>';
const break_10s = '<break time="10s"/>';
const slow_speech = '<prosody rate="slow">';
const prosody_end = '</prosody>';
const pitch_n10 = '<prosody pitch="-10%">';
const pitch_n15 = '<prosody pitch="-15%">';
const pitch_med = '<prosody pitch="medium">';
const pitch_low = '<prosody pitch="low">';

module.exports = {
  EXERCISES_EN_US: [
    {
      'STRETCH': [
        `Do these exercises as I speak. ${pitch_low} start with a ${prosody_end} child pose ${pitch_low}then a ${prosody_end} cat and cow pose ${pitch_low} stretch. ${prosody_end} Kneel down on both ${pitch_med} knees ${prosody_end} ${break_2s} Sit on your ${pitch_n15} heels. ${prosody_end} ${break_3s} Lift your hands straight up into the air. ${break_1s} Fold your body over until your forehead touch the ${pitch_n10} ground. ${prosody_end}${break_2s} Straighten ${pitch_n10} out your arms. Clear your thoughts. ${prosody_end} ${break_2s} Take a deep breath. ${break_2s} And, breathe out. ${break_3s} Come up on all four of your legs and arms, into a table position. ${break_3s} Arms are perpendicular to the floor. Legs are bent at 90 degrees angle. ${break_3s} Neutralize your back by curling your spine into a cat pose or a hunchback. ${break_3s} Then, arch your back and lift your head into a cow pose. ${break_1s} Repeat a few times. ${break_10s} Add in variations as you like.`,
        `Feel free to do what feels right for your body. Straighten your legs out into a downward dog pose, an upside down v shape. ${break_3s} Stretch your back. ${break_5s} Bring your body down into a plank position for 1 second ${break_1s} and then rest on your stomach. ${break_3s} Slowly, arch up by extending your ${pitch_n10} arms.${prosody_end} ${break_5s} Stretch your back and abs. Lean towards the left and give it a stretch. Then, do the other ${pitch_n10} side. ${prosody_end} ${break_10s} Sit up an Indian position. Legs are folded in like a meditating position. ${break_2s} We are going for a left leg stretch. ${break_2s} Fold your right leg in towards your inner thighs and straighten your left leg outward to the left. ${break_2s} Take both your hands and try to touch the bottom of your left foot. ${break_5s}${break_10s} Do the other side ${break_10s} ${break_10s} Hold for 5 more seconds. ${break_5s}`,
        `Extend both legs outward into a wide v shape or split. ${break_5s} Extend your arms up in the air and straighten up your back. Hold for a few seconds. ${break_5s} Keep your back straight and bring your upper body closer to the ground. ${break_3s} You can rest your palms, elbows, or arms on the floor. Maintain the straight posture and bring the chest closer to the floor. ${break_3s} Feel the stretch on the inner thigh. ${break_10s}${break_5s} Sit up. ${break_2s} Fold both your feet in with the arches of the feet pressed onto each other. ${break_3s} You are now sitting in a butterfly position. Press your knees as far as you can towards the ground. ${break_10s}${break_10s}`,
        `Sit tall and extend both legs straight out in front of you. ${break_3s} Fold your stomache and chest over your legs and wrap your hands around your feet. ${break_5s} Stretch out your hamstrings and calf muscles. ${break_10s} Give it another 5 seconds. 5. 4. 3. 2. 1. Sit tall with your legs straight in front of you. Hug your right knee into your chest and lift your leg off the ground. ${break_3s} This is to stretch your gluteus maximus muscle. ${break_10s}${break_5s} Switch up, and do the other side. ${break_10s}${break_10s} 5 seconds left. 5. 4. 3. 2. 1. Stand tall. ${break_3s} Starting with your right leg, bend your calf leg back, ${break_1s} and use your right hand to hold onto the toes for support. ${break_3s} Your knees are pointing towards the ground. Feel the stretch in your thighs. ${break_5s}${break_10s} Switch and do the other side. ${break_10s}${break_10s} Hold for 5 more seconds. ${break_5s}`,
        `Next, let's stretch your upper arm muscles. Stand tall, and reach both hands straight up into the air, ${break_1s} shoulder width apart. ${break_2s} Bend the right arm down towards the back of your head. ${break_2s} Use your left hand and grab the right elbow. Gently pull the right elbow towards the left ${break_1s} and stretch out the arms on the right side. ${break_10s} ${break_10s}Switch it up and do the other side. ${break_10s}${break_10s} Hold for 5 more seconds ${break_5s} Next is the back spine stretch. Stand in front of a wall with about 1 arm length distance away. ${break_5s} Open your hands and place them on the wall shoulder width apart. ${break_2s} Keep your spine straight, and fold your body down towards the ground to stretch the back. ${break_3s} Keep your arms and legs straight. Feel the tensions release. ${break_10s}`,
        `Last stretch is for the calf muscles. Place your fingers on the wall at shoulder height and width apart. ${break_2s} Flex your left foot up. ${break_1s} Toes touch the wall, and the heel on the ground. ${break_2s} Your leg should be completely straight. ${break_2s} Keep a straight posture and bring your body closer to the wall. ${break_5s} This is an excellent stretch for your calf muscles. ${break_10s}${break_5s} Switch, and do the same with the other side. ${break_10s}${break_10s} Hold for 5 more seconds. ${break_5s} Shake off your body and release anything else you need to. Your stretch is now complete`
      ],
    },
  ],
};
