const break_1s = '<break time="1s"/>';
const break_2s = '<break time="2s"/>';
const break_3s = '<break time="3s"/>';
const break_5s = '<break time="5s"/>';
const break_10s = '<break time="10s"/>';
const slow_speech = '<prosody rate="slow">';
const prosody_end = '</prosody>';
const pitch_n10 = '<prosody pitch="-10%">';
const pitch_n15 = '<prosody pitch="-15%">';
const pitch_med = '<prosody pitch="medium">';
const pitch_low = '<prosody pitch="low">';

module.exports = {
  EXERCISES_EN_US: [
    {
      'STRETCH': [
        `Do these exercises as I speak. ${pitch_low} start with a ${prosody_end} child pose ${pitch_low}then a ${prosody_end} cat and cow pose ${pitch_low} stretch. ${prosody_end} ${slow_speech} Kneel down on both ${pitch_med} knees ${prosody_end} and sit on your ${pitch_n15} heels. ${prosody_end} ${break_3s} Lift your hands straight up into the air. ${break_1s} Fold your body over until your forehead touch the ${pitch_n10} ground. ${prosody_end}${break_2s} Straighten ${pitch_n10} out your arms. Clear your thoughts. ${prosody_end} ${break_1s} Take a deep breath. ${break_2s} And, breathe out. ${break_2s} Come up on all four of your legs and arms, into a table position. ${break_2s} Arms are perpendicular to the floor. Legs are bent at 90 degrees angle. ${break_3s} Neutralize your back by curling your spine into a cat pose or a hunchback. ${break_2s} Then, arch your back and lift your head into a cow pose. ${break_1s} Repeat a few times. ${break_10s} Add in variations as you like. ${prosody_end}`,
        `Feel free to do what feels right for your body. ${slow_speech} Straighten your legs out into a downward dog pose, an upside down v shape. ${break_3s} Stretch your back. ${break_5s} Bring your body down into a plank position for 1 second ${break_1s} and then rest on your stomach. ${break_3s} Slowly, arch up by extending your ${pitch_n10} arms.${prosody_end} ${break_5s} Stretch your back and abs. Lean towards the left and give it a stretch. Then, do the other ${pitch_n10} side. ${prosody_end} ${break_10s} Sit up an Indian position. ${break_2s} We are going for a left leg stretch. ${break_2s} Fold your right leg in towards your inner thighs and straighten your left leg outward to the left. ${break_2s} Take both your hands and try to touch the bottom of your left foot. ${break_5s} Do the other side ${break_10s} Hold for 5 more seconds. ${break_5s} ${prosody_end}`,
        `Extend both legs outward into a wide v shape or split. ${break_5s} Extend your arms into the air and straighten up your back. Hold for a few seconds. ${break_5s} Keep your back straight and bring your upper body closer to the ground. ${break_3s} You can rest your palms, elbows, or arms on the floor. Maintain the straight posture and bring the chest closer to the floor. ${break_3s} Feel the stretch on the inner thigh. ${break_10s} Sit up. ${break_2s} Fold both your feet in with the arches of the feet pressed onto each other. ${break_3s} You are now sitting in a butterfly position. Press your knees as far as you can towards the ground. ${break_10s}`,
        `Sit tall and extend both legs straight out in front of you. ${break_3s} Fold your stomache and chest over your legs and wrap your hands around your feet. ${break_5s} Stretch out your hamstrings and calf muscles. Give it another 5 seconds. 5. 4. 3. 2. 1. Sit tall with your legs straight in front of you. Hug your right knee into your chest. ${break_3s} This is to stretch your gluteus maximus muscle. ${break_5s} Switch up, and do the other side. ${break_10s} 5 seconds left. 5. 4. 3. 2. 1. Stand tall. ${break_2s} Starting with your right leg, bend your calf back, ${break_1s} and use your right hand to hold onto the toes for support. ${break_3s} Your knees are pointing towards the ground. Feel the stretch in your thighs. ${break_5s} Switch and do the other side. ${break_10s} Hold for 5 more seconds. ${break_5s}`,
        `Next, let's stretch your upper arm muscles. Stand tall, and reach both hands straight up into the air, ${break_1s} shoulder width apart. ${break_2s} Bend the right arm down towards the back of your head. ${break_2s} Use your left hand and grab the right elbow. Gently pull the right elbow towards the left ${break_1s} and stretch out the arms on the right side. ${break_10s} Switch it up and do the other side. ${break_10s} Hold for 5 more seconds ${break_5s} Next is the back spine stretch. Stand in front of a wall with about 1 arm length distance away. ${break_5s} Open your hands and place them on the wall shoulder width apart. ${break_2s} Keep your spine straight, and fold your body down towards the ground to stretch the back. ${break_3s} Keep your arms and legs straight. Feel the tensions release. ${break_10s}`,
        `Last stretch is for the calf muscles. Place your fingers on the wall at shoulder height and width apart. ${break_2s} Flex your left foot up with your toes touching the wall and your heel on the ground. ${break_2s} Your leg should be completely straight. ${break_2s} Keep a straight posture and bring your body closer to the wall. ${break_5s} This is an excellent stretch for your calf muscles. ${break_5s} Switch, and do the same with the other side. ${break_10s} Hold for 5 more seconds. ${break_5s} Shake off your body and release anything else you need to. Your stretch is now complete.`
      ],
    },
    {
      'LEGS': [
        `Squats, 15 repetitions. You have 1 minute. ${break_2s} Stand with feet hip distance apart. ${break_2s} Take one wide step to the right with your right foot. ${break_1s} You can keep your hands together, or apart and out in front of you. ${break_2s} Try not to move your knees. Using your hips and butt, slowly sit back until you reach a 90 degree angle. ${break_3s} Stand up and repeat ${break_10s} Squats target the thighs and gluteus maximus. ${break_10s} 15 more seconds. ${break_10s} 5 more seconds. ${slow_speech} 5. 4. 3. 2. 1. ${prosody_end}`,
        `Lunges, 12 repetitions on each foot. You have 1 minute. ${break_2s} Stand up with feet hip distance apart. ${break_2s} Starting with the right foot, take one big step forward. Both feet should be pointing forward. ${break_2s} To go down into the lunge, bend the back leg to a 90 degree angle. Your knee should almost touch the ground. ${break_5s} Switch and do the other side. And, repeat ${break_10s} Feel the burn on the right thigh muscles. ${break_10s} Inhale and exhale on every step you take. ${break_10s} 5 more seconds. ${slow_speech} 5. 4. 3. 2. 1. ${prosody_end}`,
        `Jump Squats, 15 repetitions. You have 1.5 minutes. ${break_2s} Stand with feet apart and toes pointing forward. ${break_2s} Keep your hands together, ${break_1s} aligned at the center of your chest. ${break_2s} Using your hips, ${break_1s} sit back into a 90 degree angle without moving your calves. ${break_2s} Launch yourself into the air. As you jump, straighten your arms. ${break_2s} Return your hands together as you land on the ground. ${break_10s} Focus on feeling the burn in your leg muscles all around. ${break_10s} 40 seconds left. ${break_10s} If you finished early, pace yourself around the room to catch your breath. ${break_10s} 10 seconds left. ${slow_speech} 10. 9. 8. 7. 6. 5. 4. 3. 2. 1. ${prosody_end}`,
        `Medicine ball squats, 15 repetitions. You have 1 minute. ${break_5s} Stand with your feet apart and pointing forward. ${break_2s} The medicine ball should be on the ground in between your legs. ${break_2s} Sit backwards with your butt. Try to keep the calves and knees still. Keep your arms straight for the entire exercise. Pick up the ball and breathe in. ${break_2s} As you lift it up, breathe out until the arms are parallel to the ground. ${break_2s} Then, keep moving until the arms are straight into the air. ${break_2s} Now, stand up from your squat position. ${break_2s} Return to your squat, and reverse the procedure. ${break_10s} 5 seconds left. ${slow_speech} 5. 4. 3. 2. 1. ${prosody_end}`,
        `X Jump, 15 repetitions. You have 1 minute and 15 seconds. ${break_2s} Begin by sitting back into a squat position. ${break_2s} Launch yourself into the air with your arms up and form an X shape. ${break_2s} When you land on the ground, tap the left foot with your right hand. ${break_2s} Jump back into air and do the other side. ${break_10s} This is a cardio and toning exercise. It targets the legs, hips, and love handles. ${break_10s} 15 seconds remaining. ${break_10s} 5 seconds left. ${slow_speech} 5. 4. 3. 2. 1. ${prosody_end}`,
        `Mountain Climber, 20 repetitions on each side. You have 45 seconds. ${break_2s} This is 40 repetitions total. ${break_2s} Start in a plank position. ${break_2s} Bring one foot directly below your chest. ${break_2s} Both feet should be on the toes. Heels are lifted off the ground. ${break_2s} In one motion, switch the legs into the other position at the same time. ${break_2s} Repeat ${break_10s} 15 seconds remaining. ${break_10s} ${slow_speech} 5. 4. 3. 2. 1. ${prosody_end}`,
        `Jump lunges, 15 repetitions on each side. You have 1 minute. ${break_2s} Start by standing up straight with feet fist size apart. ${break_2s} Align your hands at the center of your chest. Hop into a lunge position and immediately bend and drop the back leg until it reaches a 90 degree angle. ${break_3s} Propel your body up and switch your legs. ${break_2s} 25 seconds left. ${break_10s} Do as much as you can. ${break_10s}  ${slow_speech} 5. 4. 3. 2. 1. ${prosody_end}`,
        `Wide plee-A squats, 15 repetitions. You have 1 minute. ${break_2s} This exercise will target the inner thigh muscles. ${break_2s} Begin standing with your feet wide apart from each other. Feet are 45 degrees pointing outward. Heels point inwards towards each other. ${break_2s} Squat down 90 degrees into a plea-A. ${break_2s} Plee-A is a movement in ballet. ${break_10s} Increase or decrease the angle of your feet to target different muscles. ${break_10s} This exercise target inner thigh fat and reduce the friction between the legs. ${break_10s} ${slow_speech} 5. 4. 3. 2. 1. ${prosody_end}`,
        `Sumo squats, 15 repetitions. You have 1 minute. ${break_2s} Stand with your feet wide apart from each other. ${break_2s} Using your butt, sit back into squat position. Hold for a few seconds. ${break_3s} Stand back up. And, repeat. ${break_10s} The wider stance intensify the workout. ${break_10s} Coordinate your breathing to enhance the workout. Inhale while standing up, and exhale as you squat down. ${break_10s} ${slow_speech} 5 more seconds. 5. 4. 3. 2. 1. ${prosody_end}`,
        `Burpees, 15 repetitions. 1 minute. ${break_2s} Burpees are also known as squat thrust. ${break_2s} Begin standing up. ${break_2s} Then squat down, and place your palms flat on the ground next to your feet. ${break_1s} Do not squat all the way down where your gluteus maximus almost touch the floor. ${break_1s} Hop your legs back into a plank position, ${break_2s} and then hop again to return to your squat. ${break_2s} Jump into the air as you rise up, and reach for the ceilings with your arms. ${break_2s} When you return to the ground, land on your feet, and immediately put your palms onto the ground and hop back into a plank. ${break_10s} 5 seconds left. ${slow_speech} 5. 4. 3. 2. 1. ${prosody_end}`,
      ],
    },
  ],
};
