var stretch = [
  "Do these exercises as I speak because my speech is timed with your progress. Kneel down, with your toes pointed, and the bridge of your foot against the ground. Sit with your butt on the arches of your feet, and lift your hands straight up into the air. Fold your body over until your forehead rest on the ground. Straighten out your arms and open your palms. Extend your fingers and reach as far as you can. Clear your thoughts and relax. Take a deep breath, and, exhale slowly, until your last breath is out.",
  "Come up to a table position with only your palms and knees on the ground. Your arms should be straightened up in the air forming a 90 degree angle with the floor. You legs should be bent in a 90 degree angle with your knees and toes touching the ground. Neutralize your spine by curling your spine into a cat pose, and then, arch your spine into a cow pose. Interchange the poses a few times. You are welcome to add in other stretches. These are just guidelines. Feel free to do what feels right for your body. Straighten your legs out into a downward dog. Your body is in an upside down v position. Give your full body a stetch and keep your spine straight. Hold for 5 more seconds. 5, 4, 3, 2, 1. Bring your body down into a plank and rest your body on the ground.",
  "Straighten your body and lay on your stomach. Your palms should be on the ground next to your face, and slowly, push up to stretch your spine and ab muscles. Take your time and stretch your muscles out. Lean towards the left and give it a stretch. Then, lean towards the right and give it a stretch. 5 seconds. 5, 4, 3, 2, 1.",
  "Sit up an indian position. Straighten your left leg outward towards the left as far as you can. Fold in your right leg with your toes touching or almost touching your left leg inner thighs. Give it a good stretch on the left leg. Take both your hands and try to touch the bottom of your left foot. Hold, hold, hold. Come up, and do the other side. Fold in your left leg, and straighten out your right legt towards the right as far as you can. Reach your hands out and wrap your fingers around the foot. Give it a good stretch.",
  "Extend both legs outward into a v shape or split. Push both legs towards the opposite ends as far as you can. Extend your arms into the air and straighten up your back. Focus on your posture. Keeping your posture straight and arms straight, slowly, bring your upper body closer to the ground. When you arms are almost towards the ground, bend them and rest them comfortably. Try to maintain the straight posture and bring the chest to the ground. Feel the stretch on the inner thigh. 5 seconds. 5, 4, 3, 2, 1.",
  "Come up, and fold both your feet in with the arches of the feet pressed onto each other. You are now sitting in a butterfly position. Press your knees as far as you can towards the ground. You can fold your body forward to stretch your spine. 5 more seconds. 5, 4, 3, 2, and 1.",
  "Extend both legs straight out in front of you. Your body should be in an upward L shape now. Fold over and wrap your hands around your feet. Stretch out your hamstrings and calf muscles. Give it another 5 seconds. 5, 4, 3, 2, 1.",
  "Cross your right leg over your left thigh. Then, take both arms and hug the knee and bring it into your chest for a deep hug. This is to stretch your gluteus maximus muscle. In other words, your booty. 5, 4, 3, 2, 1. Switch up, and do the other side. Hug in the left knee, and, feel the muscles stretch. 5 seconds left. 5, 4, 3, 2, 1.",
  "Hop on up with both feet on the ground next to each other. Starting with your right leg, bend your calf back, and use your right hand to hold onto the toes for support. The right heel of the foot should be able to touch your butt muscles, and your knees are pointing towards the ground. We are now stretching your thigh muscles. 5 seconds left. 5, 4, 3, 2, 1. Switch and do the other side. Bend the left calf back, and use your left hand to hold onto your toes for support. Make sure your knees are pointing straight down onto the ground. 5 seconds more to go. 5, 4, 3, 2, 1.",
  "Reach both hands straight up into the air. Bend the right arm down towards the back of your head, and reach down towards your spine. Use your left hand and grab the right elbow. Pull the right elbow towards the left and stretch out the arms on the right side. Lean towards the left for a deeper stretch on your right side. 5 seconds. 5, 4, 3, 2, 1. Switch it up and do the other side. Feel the stretch and the tensions being released. We will hold for another 5 seconds. 5, 4, 3, 2, 1.",
  "Stand in front of a wall with about 1 arm length distance away. Open the palms of your hand and place them on the wall similar to a wall pushup position. Keep your spine straight, and fold your body down towards the ground to stretch the back. Feel the tensions release on your back, the joints, and arms. 5 seconds. 5, 4, 3, 2, 1.",
  "Last stretch. Let your arms down to shoulder height with fingers lightly touching the wall. Flex your left foot up with your toes touching the wall and your heel on the ground. Your leg should be completely straight. Keep a straight posture and bring your body closer to the wall. This is an excellent stretch for your calf muscles. Give it about 5 more seconds. 5, 4, 3, 2, 1. Switch, and do the same with the other side. This is a great stetch to avoid cramps. 5 seconds remaining. 5, 4, 3, 2, 1. Shake off your body and release anything else you need to. Your stretch is now complete. "
]

var first_time = "This program is built for you to listen to the instructions and perform the action immediately after the exercise is mentioned. As you are exercising, I will give advice on how to do the exercise properly. If this is your first time, you might not be able to follow as quickly and may need to replay the exercise. Keep yourself hydrated before each exercise."

var legs = [
  "Squats, 15 repetitions. You have 1 minute. Stand with feet hip distance apart. With your right foot, take one wide step to the right, and keep your feet pointing foward. As for your hands, you can keep it together, or apart and out in front of you. Keep your feet firm onto the ground and stabilize your calves and knees. Try not to move your knees. Using your hips and butt, slowly sit back until you reach a 90 degree angle. Squats target the hamstrings, quadriceps, and gluteus maximus. 10 seconds left. 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.",
  "Lunges, 12 repetitions on each foot. You have 1 minute. Stand up with feet hip distance apart. Starting with the right foot, take one big step forward. Both feet should be pointing in front of you. To go down into the lunge, focus on bending the leg behind you until it reaches a 90 degree angle. Your knee should almost touch the ground. Feel the burn on the right thigh muscles and focus on strengthing and toning this area. Inhale and exhale on every step you take. Switch and do the other side. 10 more seconds. 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.",
  "Jump Squats, 15 repetitions. You have 1.5 minutes. Stand with feet apart and pointing forward. Keep your hands together aligned at the center of your chest. With your feet firm on the ground, sit back into a 90 degree angle without moving your calves. Launch yourself into the air like the superhero, iron man. When you are in the air, your hands should swing back straight down, and then return together as you land on the ground. Focus on feeling the burn in your leg muscles all around. 50 seconds left. If you finished early, use the remaining time to catch your breath. You can walk around wherever you are to shake off the exercise. 10 seconds left. 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.",
  "Medicine ball squats, 15 repetitions. You have 1 minute. Stand with your feet apart and pointing forward, and the medicine ball should be on the ground in between your legs. Sit backwards with your butt and try to keep the calves and knees still. Keep your arms straight for the entire exercise. Pick up the ball and breathe in. As you lift it up, breath out until the arms are parallel to the ground. Then, keep moving until the arms are straight into the air. Now, stand up from your squating position and reverse the procedure. Squat back down, and move the medicine ball back towards the ground. The entire motion is a half circle with your arms as a pivoting point. Control your breathing. 5 seconds left. 5, 4, 3, 2, 1.",
  "X Jump, 15 repetitions. You have 1 minute and 15 seconds. Begin by sitting back into a squating position, and launch yourself into the air into a X position. Your arms should be extended into the air. When you land on the ground, the right fingers will tap the left foot on the ground. Jump back into air and do the other side. 60 seconds left. Feel the burn on each foot. This is both a cardio and toning exercise. Your heart beat should be increasing while your thighs will be burning. This will also will lightly workout your hips and love handles. Focus on doing quality over quantity. Do as much as you can by the time is up. If you finish early, use the remaining time to catch on your breath. 20 seconds remaining. Do not sit down after this exercise. Pace yourself around to return to normal heartbeat. 10 seconds left. 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.",
  "Mountain Climber, 20 repetitions on each side. You have 45 seconds. This is 40 total. Start in a plank position, and bring one foot directly below your chest. Both feet should be on the toes with the heel lifted off the ground. In one motion, switch the legs into the other position at the same time. 15 seconds remaining. It is okay if you are unable to complete the entire set. 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.",
  "Jump lunges, 15 repetitions on each side. You have 1 minute. This exercise needs some attention to balancing. Start by standing up straight with feet fist size apart, and your hands together aligned at the center of your chest. Hop into a lunge position and immediately bend the back leg until it reaches a 90 degree angle. Using this bend, propel yourself up and switch your legs. 25 seconds left. This exercise will increase your heart rate and burn the thigh muscles. Keep going, you are almost there. 15 seconds left. If you have finish earlier, push yourself to do more. If you have not, then it's okay. Just keep practicing. 5, 4, 3, and 2, and 1.",
  "Split Squats, 10 repetitions. You have 30 seconds. Start by standing with feet hip distance apart. Align your hands together at the center of your chest. Hop and land with your feet apart. Sit back into a squat. Then, hop and return to your standing position. Switch back and forth until you finish your repetitions. 10 seconds left. 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.",
  "Wide plie squats, 15 repetitions. You have 1 minute. This exercse will target the inner thigh muscles. Begin standing with your feet wide apart from each other. Point your feet outwards, and your heels inwards towards each other. Squat down into a plie. Plie is a movement in ballet. Notice which muscles are burning. Increase or decrease the angle of your feet to target the muscles you want to work out. 25 seconds left. Keep your spine straight. This exercise will shape up your legs and get rid of those inner thigh fat that rub against each other. You should almost be done, or, have already finished. 10 seconds countdown. 10, 9, 8, 7, 6, 5, 4, 3, 2, 1.",
  "Sumo squats, 15 repetitions. You have 1 minute. Stand with your feet wide apart from each other. Using your butt, sit back into squat position. The wider stance intensify the workout, and reach muscles in other areas outside of the regular squat exercise. 30 seconds left. Keep going. You will be there in no time. Focus on strengthening your thigh muscles. Bend down to the full 90 degrees. You can go lower if you like and take notice of the different muscles activiated. You can coordinate your breathing as well to enhance the workout. Inhale while standing up, and exhale as you squat down. 10 seconds left. 10, 9, 8, 7, 6, 5, 4, and 3, and 2, and 1."
]

var break_time = "Take a 3 minute break and hydrate yourself if you need to. Relax and stretch. Do anything that makes you feel comfortable. When you are ready say continue."
var finish_workout = "Your workout is now complete. It is recommended for you to stretch your muscles after each workout."
